allow Python 3.4 test to fail for the time being
Right now, these tests fail with a conda dependency error:

UnsatisfiableError: The following specifications were found to be in conflict:
  - numpy 1.14* -> python >=2.7,<2.8.0a0
  - python 3.4*