MAINT: PR 3398 revisions
* adjust Azure CI to also test wheel builds
for Python 3.7, 3.9

* try bumping up the minimum Cython version
used in `pyproject.toml` because of this
observed error with MDAnalysis wheel build
test suite:
```
AttributeError: type object 'gsd.fl.GSDFile' has no attribute
'__reduce_cython__'
```

* add `pyproject.toml` placeholder entries for Python 3.7
and 3.9 as well; let's see how CI does with these..