Improved AG IndexError message
From:
IndexError: list index out of range
To:
IndexError: Index 758 is out of bounds for AtomGroup with size 382

Moves from normal Python IE to numpy like one

Reworded a few __add__ TypeErrors

Moved to using isinstance instead of type() == something